dtzar/helm-kubectl

.travis.yml, Dockerfile, README.md
- helm 2.5.1
- kubectl 1.7.2
- Alpine 3.6
=> Update to 2.5.1

.travis.yml, Dockerfile, README.md
- helm 2.6.0
- kubectl 1.7.4
- alpine 3.6
=> helm 2.6.0, kubectl 1.7.4

.travis.yml, Dockerfile, README.md
- helm 2.6.1
- kubectl 1.7.6
- alpine 3.6
=> helm 2.6.1, kubectl 1.7.6

.travis.yml, Dockerfile, README.md
- helm 2.7.2
- kubectl 1.8.3
- alpine 3.6
=> helm 2.7.2, kubectl 1.8.3

.travis.yml, Dockerfile, README.md
- helm 2.8.0
- kubectl 1.9.2
- alpine 3.7
=> helm 2.8.0, kubectl 1.9.2

.travis.yml, Dockerfile, README.md
- helm 2.8.1
- kubectl 1.9.2
- alpine 3.7
=> helm 2.8.1, kubectl 1.9.2

.travis.yml, Dockerfile, README.md
- helm 2.8.2
- kubectl 1.9.4
- alpine 3.7
=> helm 2.8.2, kubectl 1.9.4

Dockerfile
- Use wget instead of curl
- Untar on fly
=> Minor improvements and simplifications

.travis.yml, Dockerfile, README.md
- helm 2.9.0
- kubectl 1.10.2
- alpine 3.7
=> helm 2.9.0, kubectl 1.10.2

.travis.yml, Dockerfile, README.md
- helm 2.10.0
- kubectl 1.11.2
- alpine 3.8
=> helm 2.10.0, kubectl 1.11.2, alpine 3.8

.travis.yml, Dockerfile, README.md
- helm 2.11.0
- kubectl 1.11.3
- alpine 3.8
=> helm 2.11.0, kubectl 1.11.3

Dockerfile
- To have git working on `CircleCi` we need to add `openssh`
=> Add openssh

.travis.yml, Dockerfile, README.md
=> helm 2.13.1, kubectl 1.13.4, alpine 3.9

.travis.yml, Dockerfile, README.md
=> helm 3.0.0, kubectl 1.16.2

.travis.yml, Dockerfile, README.md
Also upgraded Alpine to 1.11.x
=> helm 3.0.3, kubectl 1.17.2

.travis.yml, Dockerfile, README.md
We need a bugfix in 3.1.0, which just dropped an hour ago. Trying to get the ball rollin' :)
=> helm 3.1.0, kubectl 1.17.3

.travis.yml, Dockerfile, README.md
Hey,
Helm 3.2.1 has an important fix for me, so I bumped the version to get access to the new goodness ;)
D
=> Bump to helm 3.2.1

.travis.yml, Dockerfile, README.md
* Update to latest version of Helm, Kubectl.
* Updated Alpine to 3.12
=> Helm 3.3.4, and Kubectl 1.19.2 Support

.travis.yml
* Fix failure during travis CI build.
=> Fix for build failure.

.travis.yml, Dockerfile, README.md
=> helm 3.5.0, kubectl 1.20.2

.travis.yml, Makefile, README.md
* Upgrade Helm to 3.5.3
* Upgrade Kubectl to 1.20.4
=> Upgrade Helm to 3.5.3 and kubectl to 1.20.4

.travis.yml
- Fixes #88 
If someone else wants to anchor and alias the travis yaml to not DRY with the docker build, have at it.
=> Travis only push images on master

.travis.yml, Dockerfile, Makefile, README.md
* Support for Helm 3.6.3 released yesterday.
=> Helm 3.6.3

.github/workflows/dockerhub-description.yml, .github/workflows/image-build-push.yaml, README.md
- Allows GH Workflow manual trigger, trigger on release
- Switches Travis to Github Action badge
- Adds Dockerhub description update workflow
=> Update GH Workflow, Badge

.github/workflows/image-build-push.yaml, Dockerfile, Makefile, README.md
* Updated Helm to 3.7.2
* Updated k8s to 1.23.0
* Updated Alpine to 3.15.0
=> Support for Helm 3.7.2 and k8s 1.23.0

.github/workflows/image-build-push.yaml, Dockerfile, Makefile, README.md
Updated Helm to 3.8.0
Updated k8s to 1.23.2
Added `apk -U upgrade` to update base packages.
=> Support for Helm 3.8.0 and k8s 1.23.2

.github/workflows/image-build-push.yaml, Makefile, README.md
* Support for helm 3.8.2
* Support for k8s 1.23.5
=> Support for Helm 3.8.2 and K8s 1.23.5
